CREATE TABLE IF NOT EXISTS ai_strategic_plans (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, plan_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  planning_only BOOLEAN NOT NULL DEFAULT true, no_autonomous_execution BOOLEAN NOT NULL DEFAULT true, no_customer_contact BOOLEAN NOT NULL DEFAULT true, no_pricing_changes BOOLEAN NOT NULL DEFAULT true, requires_human_approval BOOLEAN NOT NULL DEFAULT true, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS ai_okr_plans (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, plan_payload JSONB NOT NULL DEFAULT '{}'::jsonb, planning_only BOOLEAN NOT NULL DEFAULT true, no_autonomous_execution BOOLEAN NOT NULL DEFAULT true, no_customer_contact BOOLEAN NOT NULL DEFAULT true, no_pricing_changes BOOLEAN NOT NULL DEFAULT true, requires_human_approval BOOLEAN NOT NULL DEFAULT true, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS ai_strategic_initiatives (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, initiatives_payload JSONB NOT NULL DEFAULT '{}'::jsonb, planning_only BOOLEAN NOT NULL DEFAULT true, no_autonomous_execution BOOLEAN NOT NULL DEFAULT true, no_customer_contact BOOLEAN NOT NULL DEFAULT true, no_pricing_changes BOOLEAN NOT NULL DEFAULT true, requires_human_approval BOOLEAN NOT NULL DEFAULT true, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS ai_dependency_graphs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, graph_payload JSONB NOT NULL DEFAULT '{}'::jsonb, planning_only BOOLEAN NOT NULL DEFAULT true, no_autonomous_execution BOOLEAN NOT NULL DEFAULT true, no_customer_contact BOOLEAN NOT NULL DEFAULT true, no_pricing_changes BOOLEAN NOT NULL DEFAULT true, requires_human_approval BOOLEAN NOT NULL DEFAULT true, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS ai_resource_allocations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, allocation_payload JSONB NOT NULL DEFAULT '{}'::jsonb, planning_only BOOLEAN NOT NULL DEFAULT true, no_autonomous_execution BOOLEAN NOT NULL DEFAULT true, no_customer_contact BOOLEAN NOT NULL DEFAULT true, no_pricing_changes BOOLEAN NOT NULL DEFAULT true, requires_human_approval BOOLEAN NOT NULL DEFAULT true, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS ai_quarterly_plans (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, quarterly_payload JSONB NOT NULL DEFAULT '{}'::jsonb, planning_only BOOLEAN NOT NULL DEFAULT true, no_autonomous_execution BOOLEAN NOT NULL DEFAULT true, no_customer_contact BOOLEAN NOT NULL DEFAULT true, no_pricing_changes BOOLEAN NOT NULL DEFAULT true, requires_human_approval BOOLEAN NOT NULL DEFAULT true, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS ai_growth_plans (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, growth_payload JSONB NOT NULL DEFAULT '{}'::jsonb, planning_only BOOLEAN NOT NULL DEFAULT true, no_autonomous_execution BOOLEAN NOT NULL DEFAULT true, no_customer_contact BOOLEAN NOT NULL DEFAULT true, no_pricing_changes BOOLEAN NOT NULL DEFAULT true, requires_human_approval BOOLEAN NOT NULL DEFAULT true, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS ai_strategic_memory (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, memory_key TEXT NOT NULL, memory_value JSONB NOT NULL DEFAULT '{}'::jsonb, planning_only BOOLEAN NOT NULL DEFAULT true, no_autonomous_execution BOOLEAN NOT NULL DEFAULT true, no_customer_contact BOOLEAN NOT NULL DEFAULT true, no_pricing_changes BOOLEAN NOT NULL DEFAULT true, requires_human_approval BOOLEAN NOT NULL DEFAULT true, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
