events {}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  server {
    listen 80;
    server_name as6.ru;

    return 301 https://$host$request_uri;
  }

  server {
    listen 443 ssl;
    server_name as6.ru;

    ssl_certificate /etc/letsencrypt/live/as6.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/as6.ru/privkey.pem;

    location / {
      root /usr/share/nginx/html;
      index index.html;
      try_files $uri /index.html;
    }

    location /api/ {
      proxy_pass http://backend:3001/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
