CREATE TABLE IF NOT EXISTS ai_enterprise_coordination_runs (
  id BIGSERIAL PRIMARY KEY,
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  coordination_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  coordination_only BOOLEAN NOT NULL DEFAULT true,
  no_autonomous_execution BOOLEAN NOT NULL DEFAULT true,
  no_customer_contact BOOLEAN NOT NULL DEFAULT true,
  no_pricing_changes BOOLEAN NOT NULL DEFAULT true,
  requires_human_approval BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS ai_department_synchronization (id BIGSERIAL PRIMARY KEY, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, department_name TEXT NOT NULL, synchronization_payload JSONB NOT NULL DEFAULT '{}'::jsonb, coordination_only BOOLEAN NOT NULL DEFAULT true,no_autonomous_execution BOOLEAN NOT NULL DEFAULT true,no_customer_contact BOOLEAN NOT NULL DEFAULT true,no_pricing_changes BOOLEAN NOT NULL DEFAULT true,requires_human_approval BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS ai_initiative_routes (id BIGSERIAL PRIMARY KEY, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, initiative_key TEXT NOT NULL, route_payload JSONB NOT NULL DEFAULT '{}'::jsonb, coordination_only BOOLEAN NOT NULL DEFAULT true,no_autonomous_execution BOOLEAN NOT NULL DEFAULT true,no_customer_contact BOOLEAN NOT NULL DEFAULT true,no_pricing_changes BOOLEAN NOT NULL DEFAULT true,requires_human_approval BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS ai_dependency_resolutions (id BIGSERIAL PRIMARY KEY, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, dependency_key TEXT NOT NULL, resolution_payload JSONB NOT NULL DEFAULT '{}'::jsonb, coordination_only BOOLEAN NOT NULL DEFAULT true,no_autonomous_execution BOOLEAN NOT NULL DEFAULT true,no_customer_contact BOOLEAN NOT NULL DEFAULT true,no_pricing_changes BOOLEAN NOT NULL DEFAULT true,requires_human_approval BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS ai_executive_escalations (id BIGSERIAL PRIMARY KEY, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, escalation_key TEXT NOT NULL, escalation_level TEXT NOT NULL, escalation_payload JSONB NOT NULL DEFAULT '{}'::jsonb, coordination_only BOOLEAN NOT NULL DEFAULT true,no_autonomous_execution BOOLEAN NOT NULL DEFAULT true,no_customer_contact BOOLEAN NOT NULL DEFAULT true,no_pricing_changes BOOLEAN NOT NULL DEFAULT true,requires_human_approval BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS ai_organizational_conflicts (id BIGSERIAL PRIMARY KEY, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, conflict_key TEXT NOT NULL, severity TEXT NOT NULL, conflict_payload JSONB NOT NULL DEFAULT '{}'::jsonb, coordination_only BOOLEAN NOT NULL DEFAULT true,no_autonomous_execution BOOLEAN NOT NULL DEFAULT true,no_customer_contact BOOLEAN NOT NULL DEFAULT true,no_pricing_changes BOOLEAN NOT NULL DEFAULT true,requires_human_approval BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS ai_enterprise_coordination_memory (id BIGSERIAL PRIMARY KEY, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, memory_key TEXT NOT NULL, memory_value JSONB NOT NULL DEFAULT '{}'::jsonb, coordination_only BOOLEAN NOT NULL DEFAULT true,no_autonomous_execution BOOLEAN NOT NULL DEFAULT true,no_customer_contact BOOLEAN NOT NULL DEFAULT true,no_pricing_changes BOOLEAN NOT NULL DEFAULT true,requires_human_approval BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
