export const LIVING_LOCALES = ["ru", "en"];
export const DEFAULT_LIVING_LOCALE = "ru";

const STORAGE_KEY = "as6-living-locale";

const messages = {
  ru: {
    today: "Сегодня",
    overnight: "AS6 собрал {count} событий за сегодня и выделил главный способ улучшить результат.",
    utilities: "Настройки рабочего пространства",
    lightTheme: "Светлая тема",
    darkTheme: "Тёмная тема",
    settings: "Настройки",
    weather: "Погода",
    greeting: "Доброе утро, {name}.",
    dayReady: "Рабочий день подготовлен.",
    mainGoal: "Главная цель",
    as6Now: "AS6 сейчас",
    probability: "Вероятность успешной встречи",
    prepared: "AS6 уже подготовил",
    whyNow: "Почему именно сейчас",
    whatNext: "Что будет дальше",
    whatChanges: "Что изменится",
    intent: "Намерение",
    voiceStart: "Голосовой ввод",
    voiceStop: "Остановить голосовой ввод",
    voiceListening: "Слушаю…",
    voiceUnsupported: "Голосовой ввод не поддерживается этим браузером",
    voiceError: "Не удалось распознать речь. Проверьте доступ к микрофону.",
    sendIntent: "Передать намерение",
    switchWorkspace: "Переключить рабочее пространство",
    companySwitcher: "Компания",
    platformBrand: "AS6 AI PLATFORM",
    signOut: "Выйти из AS6 →",
    dataLoading: "AS6 обновляет рабочий контекст",
    dataReady: "Рабочий контекст актуален",
    dataError: "Часть рабочего контекста временно недоступна",
    dataStale: "Показан последний подтверждённый рабочий контекст",
    dataOffline: "Нет сети — показан последний доступный рабочий контекст",
    settingsTitle: "Профиль и фирменный стиль",
    settingsSubtitle: "Настройки применяются ко всем экранам живого пространства.",
    profileSettings: "Профиль пользователя",
    companySettings: "Компания и фирменный стиль",
    displayName: "Отображаемое имя",
    avatar: "Фотография профиля",
    avatarSize: "Размер фотографии",
    avatarSizeHint: "Размер сохраняется в профиле и применяется во всех компаниях.",
    resetAvatarSize: "Вернуть 100%",
    workspaceName: "Название компании",
    selectedCompany: "Настраиваемая компания",
    selectedCompanyHint: "Профиль пользователя общий, фирменный стиль сохраняется отдельно для каждой компании.",
    discardCompanyChanges: "Есть несохранённые изменения. Переключить компанию и отменить их?",
    companyLogo: "Логотип компании",
    companyLogoSize: "Размер логотипа",
    companyLogoSizeHint: "Размер сохраняется отдельно для каждой компании.",
    resetLogoSize: "Вернуть 100%",
    brandMode: "Режим бренда",
    brandPlatform: "Бренд платформы AS6",
    brandCoBranded: "Совместный брендинг: AS6 + {company}",
    brandCompany: "Только загруженный логотип: {company}",
    language: "Основной язык",
    imageHint: "PNG, JPG или WebP, до 1 МБ",
    chooseImage: "Выбрать файл",
    save: "Сохранить",
    saving: "Сохраняем…",
    saved: "Настройки сохранены",
    saveError: "Не удалось сохранить настройки",
    ownerOnly: "Изменять фирменный стиль могут владелец и администратор.",
    backHome: "Вернуться на главный экран",
    activityLog: "События за сегодня",
    noActivity: "Сегодня подтверждённых событий пока нет.",
    activityInsight: "Главный найденный способ",
    close: "Закрыть",
    customizeSpace: "Настроить пространство",
    layoutEditMode: "Режим настройки",
    layoutBrowserNote: "Для этой компании в текущем браузере",
    resetLayout: "Сбросить",
    cancel: "Отмена",
    done: "Готово",
    layoutSaved: "Пространство сохранено",
    layoutSaveError: "Не удалось сохранить пространство",
    layoutResetReady: "Стандартное оформление и расположение восстановлены",
    moveMainGoal: "Переместить главную цель",
    objectAppearance: "Оформление объекта",
    iconColor: "Цвет значка",
    iconSize: "Размер значка",
    labelSize: "Размер подписи",
    iconSymbol: "Символ",
    iconSymbol_original: "Исходный символ",
    iconSymbol_ring: "Кольца",
    iconSymbol_diamond: "Ромб",
    resetObjectStyle: "Сбросить объект",
    goals: "Приоритетные цели",
    currentGoal: "Текущая цель",
    chooseGoal: "Выбрать эту цель",
    goalEvidence: "Открыть основания приоритета",
    createWorkspace: "Добавить компанию",
    createWorkspaceTitle: "Новое рабочее пространство",
    companyNamePlaceholder: "Название компании",
    creatingWorkspace: "Создаём…",
    workspaceCreated: "Компания добавлена",
    workspaceLimit: "Лимит пространств по тарифу: {current} из {limit}",
    workspaceLimitReached: "Лимит компаний по текущему тарифу исчерпан",
    activePlan: "Тариф {plan} · активен",
    managePlan: "Тарифы и возможности",
    upgradePlan: "Расширить тариф",
    open: "Открыть",
  },
  en: {
    today: "Today",
    overnight: "AS6 collected {count} events today and identified the main way to improve the outcome.",
    utilities: "Workspace controls",
    lightTheme: "Light theme",
    darkTheme: "Dark theme",
    settings: "Settings",
    weather: "Weather",
    greeting: "Good morning, {name}.",
    dayReady: "Your working day is ready.",
    mainGoal: "Main goal",
    as6Now: "AS6 now",
    probability: "Probability of a successful meeting",
    prepared: "AS6 has prepared",
    whyNow: "Why now",
    whatNext: "What happens next",
    whatChanges: "What will change",
    intent: "Intent",
    voiceStart: "Voice input",
    voiceStop: "Stop voice input",
    voiceListening: "Listening…",
    voiceUnsupported: "Voice input is not supported by this browser",
    voiceError: "Speech could not be recognised. Check microphone access.",
    sendIntent: "Send intent",
    switchWorkspace: "Switch workspace",
    companySwitcher: "Company",
    platformBrand: "AS6 AI PLATFORM",
    signOut: "Sign out of AS6 →",
    dataLoading: "AS6 is refreshing business context",
    dataReady: "Business context is current",
    dataError: "Some business context is temporarily unavailable",
    dataStale: "Showing the last verified business context",
    dataOffline: "Offline — showing the last available business context",
    settingsTitle: "Profile and company branding",
    settingsSubtitle: "These settings apply to every Living Space screen.",
    profileSettings: "User profile",
    companySettings: "Company and branding",
    displayName: "Display name",
    avatar: "Profile photo",
    avatarSize: "Photo size",
    avatarSizeHint: "The size is saved in your profile and applies to every company.",
    resetAvatarSize: "Reset to 100%",
    workspaceName: "Company name",
    selectedCompany: "Company being configured",
    selectedCompanyHint: "The user profile is shared; branding is saved separately for each company.",
    discardCompanyChanges: "You have unsaved changes. Switch company and discard them?",
    companyLogo: "Company logo",
    companyLogoSize: "Logo size",
    companyLogoSizeHint: "The size is saved separately for each company.",
    resetLogoSize: "Reset to 100%",
    brandMode: "Brand mode",
    brandPlatform: "AS6 platform brand",
    brandCoBranded: "Co-branding: AS6 + {company}",
    brandCompany: "Uploaded company logo only: {company}",
    language: "Primary language",
    imageHint: "PNG, JPG or WebP, up to 1 MB",
    chooseImage: "Choose file",
    save: "Save",
    saving: "Saving…",
    saved: "Settings saved",
    saveError: "Could not save settings",
    ownerOnly: "Only workspace owners and administrators can change branding.",
    backHome: "Return to home screen",
    activityLog: "Today's events",
    noActivity: "There are no verified events today yet.",
    activityInsight: "Main identified opportunity",
    close: "Close",
    customizeSpace: "Customize space",
    layoutEditMode: "Layout edit mode",
    layoutBrowserNote: "For this company in this browser",
    resetLayout: "Reset",
    cancel: "Cancel",
    done: "Done",
    layoutSaved: "Workspace saved",
    layoutSaveError: "Could not save workspace",
    layoutResetReady: "Default appearance and layout restored",
    moveMainGoal: "Move the main goal",
    objectAppearance: "Object appearance",
    iconColor: "Icon color",
    iconSize: "Icon size",
    labelSize: "Label size",
    iconSymbol: "Symbol",
    iconSymbol_original: "Original symbol",
    iconSymbol_ring: "Rings",
    iconSymbol_diamond: "Diamond",
    resetObjectStyle: "Reset object",
    goals: "Priority goals",
    currentGoal: "Current goal",
    chooseGoal: "Choose this goal",
    goalEvidence: "Open priority evidence",
    createWorkspace: "Add company",
    createWorkspaceTitle: "New workspace",
    companyNamePlaceholder: "Company name",
    creatingWorkspace: "Creating…",
    workspaceCreated: "Company added",
    workspaceLimit: "Workspace allowance: {current} of {limit}",
    workspaceLimitReached: "Your current plan workspace allowance is full",
    activePlan: "{plan} plan · active",
    managePlan: "Plans and features",
    upgradePlan: "Upgrade plan",
    open: "Open",
  },
};

export function normalizeLivingLocale(value) {
  const normalized = String(value || "").trim().toLowerCase().slice(0, 2);
  return LIVING_LOCALES.includes(normalized) ? normalized : DEFAULT_LIVING_LOCALE;
}

export function getStoredLivingLocale(fallback = DEFAULT_LIVING_LOCALE) {
  if (typeof window === "undefined") return normalizeLivingLocale(fallback);
  try {
    return normalizeLivingLocale(window.localStorage.getItem(STORAGE_KEY) || fallback);
  } catch (_error) {
    return normalizeLivingLocale(fallback);
  }
}

export function persistLivingLocale(locale) {
  const normalized = normalizeLivingLocale(locale);
  if (typeof window !== "undefined") {
    try {
      window.localStorage.setItem(STORAGE_KEY, normalized);
    } catch (_error) {
      // The active locale still changes in memory when storage is unavailable.
    }
    document.documentElement.lang = normalized;
  }
  return normalized;
}

export function createLivingTranslator(locale) {
  const normalized = normalizeLivingLocale(locale);
  return function translate(key, values = {}) {
    const template = messages[normalized]?.[key] || messages.ru[key] || key;
    return Object.entries(values).reduce(
      (result, [name, value]) => result.replaceAll(`{${name}}`, String(value)),
      template,
    );
  };
}

export function livingIntlLocale(locale) {
  return normalizeLivingLocale(locale) === "en" ? "en-GB" : "ru-RU";
}
