export const crmActivitiesLiveLayoutMountContract = Object.freeze({
  id: "crm.activities.tasks.live-layout.mount",
  stage: "AS6_EPIC015_SLICE06_CRM_ACTIVITIES_TASKS_LIVE_LAYOUT_MOUNT",
  module: "CRM_ACTIVITIES_TASKS",
  mountedInProductionLayout: true,
  useExistingCrmLayout: true,
  useExistingCrmWorkspace: true,
  useExistingHeader: true,
  useExistingSidebar: true,
  useExistingRouter: true,
  ownRouter: false,
  ownStore: false,
  duplicateRoute: false,
  duplicatePanel: false,
  noParallelLayout: true,
  noParallelShell: true,
  storageEnabled: false,
  apiEnabled: false,
  workflowEnabled: false,
  platformMutation: false,
});
