export const crmDealsLiveLayoutMountContract = Object.freeze({
  id: "crm.deals.live-layout.mount",
  stage: "AS6_EPIC014_SLICE06_CRM_DEALS_LIVE_LAYOUT_MOUNT",
  module: "CRM_DEALS_OPPORTUNITIES",
  route: "/crm/deals",
  activeSection: "deals",
  mountedInProductionLayout: true,
  useExistingCrmLayout: true,
  useExistingCrmWorkspace: true,
  useExistingRouter: true,
  ownRouter: false,
  ownStore: false,
  duplicateRoute: false,
  duplicatePanel: false,
  noParallelLayout: true,
  noParallelShell: true,
  storageEnabled: false,
  apiEnabled: false,
  workflowEnabled: false,
  platformMutation: false,
});
