const pool=require('../../db/pool')
const { evaluateLeadState }=require('./leadStateEvaluator')
const { generateNextBestActions }=require('./nextBestActionEngine')
const { buildFollowUpStrategy }=require('./followUpStrategyEngine')
const { recommendEscalation }=require('./escalationDecisionEngine')
const { recommendSalesStage }=require('./salesStageTransitionEngine')
const { buildHandoffRecommendation }=require('./humanHandoffEngine')
async function runAutonomousSdrLoop({ sessionId, workspaceId, leadId, intelligence={}, publishEvent=()=>{} }){ const leadState=evaluateLeadState(intelligence); const actions=generateNextBestActions({ leadState, meetingIntent:intelligence.meetingIntent, objectionCategory:intelligence.objectionCategory, enterpriseSignals:intelligence.enterpriseSignals, sentiment:intelligence.sentiment }); const followup=buildFollowUpStrategy({ leadState, sentiment:intelligence.sentiment, inactivityHours:intelligence.inactivityHours }); const escalation=recommendEscalation(intelligence); const handoff=buildHandoffRecommendation({ escalation, leadState, actions }); const stage=recommendSalesStage({ leadState, actions, meetingIntent:intelligence.meetingIntent }); await pool.query('INSERT INTO ai_sdr_lead_states(workspace_id,lead_id,session_id,lead_state,payload) VALUES($1,$2,$3,$4,$5)',[workspaceId,leadId,sessionId,leadState,JSON.stringify({ intelligence })]); await pool.query('INSERT INTO ai_next_best_actions(workspace_id,lead_id,session_id,actions,payload) VALUES($1,$2,$3,$4,$5)',[workspaceId,leadId,sessionId,actions,JSON.stringify({ suggestionOnly:true,humanApprovalRequired:true })]); await pool.query('INSERT INTO ai_followup_strategies(workspace_id,lead_id,session_id,urgency_level,suggested_timing,recommended_channel,messaging_style,payload) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[workspaceId,leadId,sessionId,followup.urgencyLevel,followup.suggestedTiming,followup.recommendedChannel,followup.messagingStyle,JSON.stringify({ suggestionOnly:true })]); if(handoff) await pool.query('INSERT INTO ai_handoff_recommendations(workspace_id,lead_id,session_id,priority,owner_role,reasons,payload) VALUES($1,$2,$3,$4,$5,$6,$7)',[workspaceId,leadId,sessionId,handoff.priority,handoff.ownerRole,handoff.rationale,JSON.stringify(handoff)]); publishEvent('lead_state_updated',{ leadState,suggestionOnly:true,humanApprovalRequired:true }); publishEvent('next_best_action_generated',{ actions,suggestionOnly:true,humanApprovalRequired:true }); publishEvent('followup_strategy_generated',{ ...followup,suggestionOnly:true,humanApprovalRequired:true }); if(handoff) publishEvent('handoff_recommended',{ ...handoff,suggestionOnly:true,humanApprovalRequired:true }); publishEvent('sales_stage_recommended',{ stage,suggestionOnly:true,humanApprovalRequired:true }); return { leadState,actions,followup,escalation,handoff,stage } }
module.exports={ runAutonomousSdrLoop }
